# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3681b3ed5e0e2898aa4d23a3bb7351c64d5328e34b6b87d4a1c21ec1bc8fcffe486ba4950ac27a0c39bb18eddb4562b22ba198b002db3edbbebdd1a74b43c795

test:
  secret_key_base: 06e639d01008693dbe3c5dd06b7e4c2052b6092a2f81d5f567e8c3e316c577c9ecc1d923915f97155173db95e78afea828ffa75732bdeea0ad7f8b44ef39661f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
